### ISSUE TITLE
Check FDR implementation 

### ISSUE THREAD

**Issue by simon-shlomo** [NeurophysiologicalBiomarkerToolbox/NBT#118]

**Comment by shoutman** [comment]
nbt_MCcorrect.m, Line 77: this might be wrong
Now it only returns adjusted p's, but not the critical p

**Comment by ssimpraga** [comment]
Yes, it does: the line is 
[h, crit_p, Pc]=fdr_bh(p,q,'pdep','no');
where crit_p is the critical p value, but it's not used. You need either look at uncorrected p values and then you need crit p ("instead of" significance value q that you specified) or you can look at uncorrected p values (which are then adjusted according to your q).
