### ISSUE TITLE
visualization with different channel numbers

### ISSUE THREAD

**Issue by MonaIrrmischer** [NeurophysiologicalBiomarkerToolbox/NBT#91]
Could it be possible make plots from data with less then the standard 128 channels?

**Comment by simon-shlomo** [comment]
You mean plotting results of t-tests?

**Comment by MonaIrrmischer** [comment]
Probably best to enable most kind of plots (eg t test or  simple group averages).

**Comment by simon-shlomo** [comment]
So it is because the text with different biomarker names does not show, right?..  Easy work around until I find a better solution is to go to line 899 in nbt_selectrunstatistics.m
 umenu = text(i,-10, regexprep(bioms_name{i},'_',' '),'horizontalalignment','left','fontsize',10,'fontweight','bold');

and set the second input to -0.5 .. the names are just hidden behind the p-values

**Comment by simon-shlomo** [comment]
did it work?

**Comment by simon-shlomo** [comment]
if this was fixed please close the issue

**Comment by simon-shlomo** [comment]
assume it worked?
